/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui;

import com.core.CauThu;
import com.core.HuanLuyenVien;
import com.core.NhanVien;
import com.models.NhanVienModel;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList; //
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author CỌP
 */
public class QuanLyDoiBong extends javax.swing.JFrame {

    private DefaultTableModel dmNhanVien;
    private NhanVienModel mNhanVien;
    private NumberFormat f = NumberFormat.getInstance();

    /**
     * Creates new form QuanLyDoiBong
     */
    public QuanLyDoiBong() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnGioiTinh = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanViens = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboLoaiNhanVien = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        txtTenNhanVien = new javax.swing.JTextField();
        txtQuocTich = new javax.swing.JTextField();
        txtViTriThiDau = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSoTranThamGia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSoBanThang = new javax.swing.JTextField();
        txtLuongThoaThuan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSoNamKinhNghiem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtHeSoLuong = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPhuCap = new javax.swing.JTextField();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        ftxtNgaySinh = new javax.swing.JFormattedTextField();
        ftxtNgayVaoLam = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        lblTongLuong = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnTongLuong = new javax.swing.JButton();
        btnHienThiTheoLoai = new javax.swing.JButton();
        btnHienThiTatCa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblNhanViens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên nhân viên", "Quốc tịch", "Giới tính", "Ngày Sinh", "Ngày vào làm", "Ví trị thi đấu", "Số trận tham gia", "Số bàn thắng", "Lương thỏa thuận", "Năm kinh nghiệm", "Hệ số lương", "Phụ cấp", "Loại nhân viên", "Tổng lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNhanViens);

        jLabel1.setText("Loại nhân viên: ");

        jLabel2.setText("ID:");

        jLabel3.setText("Tên nhân viên: ");

        jLabel4.setText("Quốc tịch:");

        jLabel5.setText("Giới tính: ");

        jLabel6.setText("Ngày sinh: ");

        jLabel7.setText("Ngày vào làm: ");

        jLabel8.setText("Ví trí thi đấu: ");

        cboLoaiNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cầu thủ", "Huấn luyện viên" }));

        jLabel9.setText("Số trận tham gia: ");

        jLabel10.setText("Số bàn thắng:");

        txtLuongThoaThuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuongThoaThuanActionPerformed(evt);
            }
        });

        jLabel11.setText("Lương thỏa thuận:");

        jLabel12.setText("Số năm kinh nghiệm:");

        jLabel13.setText("Hệ số lương:");

        jLabel14.setText("Phụ cấp:");

        gbtnGioiTinh.add(rdbNam);
        rdbNam.setText("Nam");

        gbtnGioiTinh.add(rdbNu);
        rdbNu.setText("Nữ");

        jLabel15.setText("Tổng lương: ");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");

        btnCapNhat.setText("Cập nhật");

        btnTongLuong.setText("Tổng lương");

        btnHienThiTheoLoai.setText("Hiển thị theo loại");

        btnHienThiTatCa.setText("Hiển thị tất cả");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(647, 647, 647)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSoBanThang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(txtSoTranThamGia, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtLuongThoaThuan, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(66, 66, 66)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(322, 322, 322)
                                            .addComponent(jLabel14))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cboLoaiNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(rdbNam)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rdbNu))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(ftxtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtViTriThiDau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                                        .addComponent(txtQuocTich, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addComponent(ftxtNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(123, 123, 123)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel15)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(520, 520, 520)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9))))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSoNamKinhNghiem, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(txtHeSoLuong)
                                .addComponent(lblTongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnThem)
                        .addGap(64, 64, 64)
                        .addComponent(btnXoa)
                        .addGap(74, 74, 74)
                        .addComponent(btnCapNhat)
                        .addGap(73, 73, 73)
                        .addComponent(btnTongLuong)
                        .addGap(67, 67, 67)
                        .addComponent(btnHienThiTheoLoai)
                        .addGap(57, 57, 57)
                        .addComponent(btnHienThiTatCa)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboLoaiNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSoTranThamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtSoBanThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLuongThoaThuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtSoNamKinhNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(txtHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbNu))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14)
                    .addComponent(txtPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ftxtNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(lblTongLuong))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtViTriThiDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addComponent(btnTongLuong)
                    .addComponent(btnHienThiTheoLoai)
                    .addComponent(btnHienThiTatCa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLuongThoaThuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuongThoaThuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuongThoaThuanActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        boolean gioiTinh = false;
        if (rdbNam.isSelected()) {
            gioiTinh = true;
        }
        if (cboLoaiNhanVien.getSelectedItem().toString().equalsIgnoreCase("Cầu thủ")) {
            mNhanVien.add(new CauThu(txtViTriThiDau.getText().trim(), Integer.parseInt(txtSoTranThamGia.getText().trim()),
                    Integer.parseInt(txtSoBanThang.getText().trim()), Double.parseDouble(txtLuongThoaThuan.getText().trim()),
                    txtTenNhanVien.getText().trim(), txtQuocTich.getText().trim(), gioiTinh, convertStringToDate(ftxtNgaySinh.getText().trim()),
                    convertStringToDate(ftxtNgayVaoLam.getText().trim())), Integer.parseInt(txtID.getText().trim()));
        } else {
            mNhanVien.add(new HuanLuyenVien(Integer.parseInt(txtSoNamKinhNghiem.getText().trim()), Double.parseDouble(txtHeSoLuong.getText().trim()), Double.parseDouble(txtPhuCap.getText().trim()), Integer.parseInt(txtID.getText().trim())));
        }
        loadDataIntoTable();
    }//GEN-LAST:event_btnThemActionPerformed
    private Date convertStringToDate(String str) {
        try {
            return new SimpleDateFormat("yyyy-mm-dd").parse(str);
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyDoiBong.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDoiBong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDoiBong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDoiBong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDoiBong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDoiBong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHienThiTatCa;
    private javax.swing.JButton btnHienThiTheoLoai;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTongLuong;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoaiNhanVien;
    private javax.swing.JFormattedTextField ftxtNgaySinh;
    private javax.swing.JFormattedTextField ftxtNgayVaoLam;
    private javax.swing.ButtonGroup gbtnGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTongLuong;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JTable tblNhanViens;
    private javax.swing.JTextField txtHeSoLuong;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLuongThoaThuan;
    private javax.swing.JTextField txtPhuCap;
    private javax.swing.JTextField txtQuocTich;
    private javax.swing.JTextField txtSoBanThang;
    private javax.swing.JTextField txtSoNamKinhNghiem;
    private javax.swing.JTextField txtSoTranThamGia;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtViTriThiDau;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        dmNhanVien = (DefaultTableModel) tblNhanViens.getModel();
        tblNhanViens.setModel(dmNhanVien);

        mNhanVien = new NhanVienModel();
        dinhDangCacTruongNgayThang();
        //hiển thị form chính giữa màn hình
        setLocationRelativeTo(null);
    }

    private void dinhDangCacTruongNgayThang() {
        try {
            MaskFormatter mf = new MaskFormatter("####-##-##");
            mf.setPlaceholderCharacter('_');
            ftxtNgaySinh.setFormatterFactory(new DefaultFormatterFactory(mf));
            ftxtNgayVaoLam.setFormatterFactory(new DefaultFormatterFactory(mf));
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyDoiBong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void xoaDuLieuCu() {
        while (dmNhanVien.getRowCount() > 0) {
            dmNhanVien.removeRow(0);
        }
    }

    private void loadDataIntoTable() {
        loadData(mNhanVien.getAll());
    }

    private void loadData(ArrayList<ArrayList> arrValues) {
        String viTriThiDau, soTranThamGia, soBanThang, luongThoaThuan,
                soNamKinhNghiem, heSoLuong, phuCap, loaiNhanVien, tongLuong;

        ArrayList<NhanVien> nhanViens = arrValues.get(0);
        ArrayList<String> iDs = arrValues.get(1);
        int index = -1;

        for (NhanVien nhanVien : nhanViens) {
            index++;
            if (nhanVien instanceof CauThu) {
                CauThu cauThu = (CauThu) nhanVien;
                viTriThiDau = cauThu.getViTriThiDau();
                soTranThamGia = "" + cauThu.getSoLuotTranThamGia();
                soBanThang = "" + cauThu.getSoBanThang();
                luongThoaThuan = "" + f.format(cauThu.getLuongThoaThuan());
                loaiNhanVien = "Cầu thủ";
                soNamKinhNghiem = heSoLuong = phuCap = "";
            } else {
                HuanLuyenVien hlv = (HuanLuyenVien) nhanVien;
                soNamKinhNghiem = "" + hlv.getSoNamKinhNghiem();
                heSoLuong = "" + hlv.getHesoLuong();
                phuCap = "" + f.format(hlv.getPhuCap());
                loaiNhanVien = "Huấn luyện viên";
                viTriThiDau = soTranThamGia = soBanThang = luongThoaThuan = "";
            }
            addOneRow(iDs.get(index), nhanVien.getTenNhanVien(), nhanVien.getQuocTich(), convertGioiTinhToString(nhanVien.getGioiTinh()), convertDateToString(nhanVien.getNgaySinh()), convertDateToString(nhanVien.getNgayVaoLam()), viTriThiDau, soTranThamGia, soBanThang, luongThoaThuan, soNamKinhNghiem, heSoLuong, phuCap, loaiNhanVien, f.format(nhanVien.tinhLuong()));
        }
    }

    private void addOneRow(
            String id, String tenNhanien, String quocTich, String gioiTinh,
            String ngaySinh, String ngayVaoLam, String viTriThiDau, String soTranThamGia,
            String soBanThang, String luongThoaThuan, String soNamKinhNghiem,
            String heSoLuong, String phuCap, String loaiNhanVien, String tongLuong
    ) {
        dmNhanVien.addRow(new Object[]{
            id, tenNhanien, quocTich, gioiTinh, ngaySinh, ngayVaoLam, viTriThiDau, soTranThamGia,
             soBanThang, luongThoaThuan, soNamKinhNghiem, heSoLuong, phuCap, loaiNhanVien, tongLuong
        });

    }

    private String convertGioiTinhToString(Boolean gioiTinh) {
        if (gioiTinh) {
            return "Nam";
        }
        return "Nữ";
    }

    private String convertDateToString(Date d) {
        return new SimpleDateFormat("yyyy-mm-dd").format(d);
    }
}
